# Generated by Django 2.2.3 on 2019-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0002_fuelsurcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelsurcharge',
            name='current_price',
        ),
        migrations.AddField(
            model_name='fuelsurcharge',
            name='input_diesel_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
