# Generated by Django 2.2.3 on 2019-12-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0004_fueldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueldata',
            old_name='surcharge_dollar',
            new_name='surcharge_per_mile',
        ),
    ]
