# Generated by Django 2.2.3 on 2019-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0005_auto_20191208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldata',
            name='linehaul_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='miles',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='rate_per_mile',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='surcharge_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='surcharge_per_mile',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='surcharge_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fueldata',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
