# Generated by Django 2.2.3 on 2019-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0006_auto_20191208_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('invoice_code', models.CharField(max_length=20)),
                ('order_number', models.CharField(max_length=20)),
                ('shipped_date', models.DateField()),
                ('received_date', models.DateField()),
                ('del_number', models.CharField(max_length=50)),
                ('shipper', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=100)),
                ('frieght_description', models.CharField(max_length=100)),
                ('frieght_weight', models.CharField(max_length=20)),
                ('frieght_quantity', models.CharField(max_length=20)),
                ('comments', models.TextField()),
                ('frieght_rate', models.IntegerField()),
                ('miles_travelled', models.IntegerField()),
                ('fsc_per_mile', models.FloatField()),
                ('fsc_percent', models.FloatField()),
                ('fsc_amount', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
