# Generated by Django 2.2.3 on 2019-12-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0008_schedule_scheduledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='excel_file',
            field=models.FileField(null='True', upload_to='uploads/schedules/'),
            preserve_default='True',
        ),
    ]
