# Generated by Django 2.2.3 on 2019-12-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0009_schedule_excel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='excel_file',
            new_name='csv_file',
        ),
    ]
