# Generated by Django 2.2.3 on 2019-12-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0010_auto_20191209_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_code',
            new_name='account_code',
        ),
    ]
