# Generated by Django 2.2.3 on 2019-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0014_auto_20191210_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fsc_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
