# Generated by Django 2.2.3 on 2019-12-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0016_auto_20191210_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsurcharge',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SiteApp.Schedule'),
        ),
    ]
